import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import basicSsl from '@vitejs/plugin-basic-ssl';
import { VitePWA } from 'vite-plugin-pwa';
import path from 'path';

export default defineConfig({
  plugins: [
    react(),
    // HTTPS in dev is required so iOS Safari / Chrome on Android will give
    // the page access to navigator.mediaDevices.getUserMedia (camera).
    // Generates a self-signed cert on first run — accept the warning on the phone.
    basicSsl(),
    VitePWA({
      // Service worker generated by Workbox. Caches the app shell + assets so
      // the PWA opens instantly on subsequent visits and survives flaky wifi.
      // `autoUpdate` means new versions install silently on next page load.
      registerType: 'autoUpdate',
      // Inject manifest directly into the bundle so /manifest.json is correct.
      manifest: {
        name: 'MuseumOS Capture',
        short_name: 'MuseumOS',
        description: 'Mobile exhibit capture for MuseumOS',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        orientation: 'portrait',
        background_color: '#ffffff',
        theme_color: '#E8751A',
        lang: 'el',
        icons: [
          { src: '/icon-192.png', sizes: '192x192', type: 'image/png' },
          { src: '/icon-512.png', sizes: '512x512', type: 'image/png' },
          { src: '/icon-512-maskable.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      workbox: {
        // Don't try to precache the /img/ tree (tens of GB). Only cache the
        // app shell. Photos are large and best served fresh.
        navigateFallback: '/index.html',
        navigateFallbackDenylist: [/^\/api\//, /^\/img\//],
        runtimeCaching: [
          {
            // Thumbnails: stale-while-revalidate so the list view feels instant
            urlPattern: /\/img\/thumbs\//,
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'thumbs',
              expiration: { maxEntries: 1500, maxAgeSeconds: 7 * 24 * 60 * 60 },
            },
          },
        ],
      },
      includeAssets: ['favicon.svg', 'icon-192.png', 'icon-512.png', 'icon-512-maskable.png', 'logo.png'],
      devOptions: {
        enabled: false, // dev server stays as-is; SW only runs in built app
      },
    }),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  server: {
    host: true, // expose on the LAN so phones on the same wifi can reach it
    port: 5174,
    proxy: {
      '/api': {
        target: 'http://localhost:3000',
        changeOrigin: true,
      },
      '/img': {
        target: 'http://localhost:3000',
        changeOrigin: true,
      },
    },
  },
});
